// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WilsonGomez_P1_AP1.DAL;

namespace WilsonGomez_P1_AP1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20201005230207_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("WilsonGomez_P1_AP1.Entidades.Ciudades", b =>
                {
                    b.Property<int>("CiudadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.HasKey("CiudadID");

                    b.ToTable("ciudades");
                });
#pragma warning restore 612, 618
        }
    }
}
